use crate::error::Error;
use curv::elliptic::curves::{Scalar, Point, Ed25519};
use multi_party_eddsa::protocols::musig2;
use solana_sdk::pubkey::Pubkey;
use multi_party_eddsa::protocols::ExpandedKeyPair;
use solana_sdk::signature::Keypair;
use solana_sdk::signature::Signer;
use crate::serialization::{AggMessage1, SecretAggStepOne, PartialSignature};
use multi_party_eddsa::protocols::musig2::{PrivatePartialNonces, PublicPartialNonces};
use solana_sdk::signature::{Signature, SignerError};
use solana_sdk::transaction::Transaction;
use crate::serialization::Error as SerError;